import React from "react";
import styled from "styled-components";
import { FaPizzaSlice, FaHamburger } from "react-icons/fa";
import { GiNoodles, GiIndiaGate } from "react-icons/gi";
import { NavLink } from "react-router-dom";

function Category() {
  return (
    //here NavLink is coverted to StyledLink.we cannot style navlink directly
    <StyledList>
      <StyledLink to={"/cuisine/Indian"}>
        <GiIndiaGate />
        <h4>Indian</h4>
      </StyledLink>
      <StyledLink to={"/cuisine/Italian"}>
        <FaPizzaSlice />
        <h4>Italian</h4>
      </StyledLink>
      <StyledLink to={"/cuisine/American"}>
        <FaHamburger />
        <h4>American</h4>
      </StyledLink>
      <StyledLink to={"/cuisine/Thai"}>
        <GiNoodles />
        <h4>Thai</h4>
      </StyledLink>
    </StyledList>
  );
}

const StyledList = styled.div`
  display: flex;
  justify-content: center;
  margin: 1rem 0rem;
  @media (max-width: 480px) {
    margin: 0.5rem 0rem;
  }
`;

const StyledLink = styled(NavLink)`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  border-radius: 50%;
  margin-right: 1.5rem;
  text-decoration: none;
  background: linear-gradient(35deg, #494949, #313131);
  width: 5rem;
  height: 5rem;
  cursor: pointer;
  transform: scale(0.8);

  h4 {
    color: #fff;
    font-size: 0.8rem;
  }

  svg {
    color: #fff;
    font-size: 1.5rem;
  }

  &.active {
    //Active is default class generated by NAVLINK
    background: linear-gradient(to right, #f27121, #e94057);

    svg,
    h4 {
      color: #fff;
    }
  }

  @media (max-width: 480px) {
    margin-right: 0.5rem;
  }
`;

export default Category;
